version: '3.8'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped

  backend:
    image: gevork23/kittygram_backend:latest
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
    depends_on:
      - db

  frontend:
    image: gevork23/kittygram_frontend:latest
    env_file: .env
    command: sh -c "cp -r /usr/share/nginx/html/. /frontend_static/ && tail -f /dev/null"
    volumes:
      - static_volume:/frontend_static

  nginx:
    image: gevork23/kittygram_nginx:latest
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/mediafiles/
    ports:
      - "9000:80"
    depends_on:
      - backend
      - frontend